### ISSUE TITLE
Grid issues in dev

### ISSUE THREAD

**Issue by onslauth** [joferkington/mplstereonet#18]
Hi,

There seems to be some issues with grid in 0.6-dev.

mplstereonet-0.5
<img width="1289" alt="mplstereonet-0 5" src="https://user-images.githubusercontent.com/44875/29413199-d9e4de36-835b-11e7-9518-061c323da037.png">

mplstereonet-0.6-dev
<img width="1303" alt="mplstereonet-0 6-dev" src="https://user-images.githubusercontent.com/44875/29413205-dc9965b6-835b-11e7-873b-531afa590844.png">

If you know where the issue might be, and can point me in the right direction, I don'd mind looking into it myself.

**Comment by joferkington** [comment]
On a side note, my apologies for the extremely belated reply.

This was related to https://github.com/joferkington/mplstereonet/pull/22  which was fixed a few years back.  The latest version incorporates the fix.
