### ISSUE TITLE
Find strike/dip based on density contour plot

### ISSUE THREAD

**Issue by theoneandonlymike** [joferkington/mplstereonet#3]
Hi,

I have a question that may be very simple but I can't figure it out.

I have quite a few density_contourf plots. Based on the default density estimation method used 'exponential_kamb' I would like to plot the plane to the most dense pole of my dataset. I could also add a text label with the dominant strike/dip set. 

Is there any way to extract the strike/dip from the density estimation? Am I missing a function that can do this?

Thanks,
Mike

**Comment by FCalderon3006** [comment]
> 

Hi! @theoneandonlymike
Can you get the code to identify multiple max point of multiple joint sets ? 
Please, can you share us ? 
The initial code was nice but I dont have an idea to get the rest of the code.
