### ISSUE TITLE
Mean-Vector function: Wrong R-Value?

### ISSUE THREAD

**Issue by tobias47n9e** [joferkington/mplstereonet#8]
Is it possible that the R-Values are all too low or that there are different ways of estimating it? Concerning this line:

 - [stereonet_math.py#L362](https://github.com/joferkington/mplstereonet/blob/f791384fb353f48e4556defcf646ff996aa5ab5b/mplstereonet/stereonet_math.py#L362)

Calculating `np.linalg.norm()` of the mean vector seems to already be the R-Value, as it is a number smaller but close to 1. Dividing by the shape would only seem necessary if the vector were much larger than 1. Using 10 vectors, the additional factor yields a r-value that is 1/10th of what I get when calculating it by hand or another program:

Using the following linears:

    dip = [37, 45, 41, 43, 39, 43, 45, 40, 37, 39]
    azimuth = [88, 89, 70, 77, 89, 85, 78, 70, 75, 77]

`np.linalg.norm(mean_vec)` gives 0.9944 and divided by the shape (=10) yields 0.09944.

**Comment by joferkington** [comment]
Hi Tobias,

Sorry for my delay in replying! You're absolutely right!

Thanks for catching this!

**Comment by tobias47n9e** [comment]
I stumbled across this while working on a function that calculates the fisher distribution. Will make a pull request for that function soon.
